#!/bin/sh
CLCLCL_JAR=$(dirname $0)/clclcl-standalone.jar
java -server -Xmx64m -Xms64m -Djava.util.logging.config.file=$(dirname $0)/logging.properties -Dawt.useSystemAAFontSettings=on -jar ${CLCLCL_JAR}
